[shell]
program = "/bin/zsh"

[keyboard]
bindings = [
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "V", mods = "Control|Shift", action = "Paste" },
]

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
size = 12
