#!/bin/sh
dots=${1:-~/.nix-profile/share/home}
home=${2:-~}
# copy/replace all config files
mkdir -p ${home}/.config
for d in $(ls ${dots}/config); do
    if [ -e ${home}/.config/$d ]; then
        rm -r ${home}/.config/$d
    fi
    cp -r ${dots}/config/$d ${home}/.config
    chmod +w ${home}/.config/$d
done
# Symlink home dir dot files
[ -e ${home}/.zshenv ] || ln -s ${dots}/.zshenv ${home}/.zshenv
# Copy the default files for environment specific configs
[ -e ${home}/.fishrc.fish ] || cp ${dots}/.fishrc.fish ${home}/.fishrc.fish
[ -e ${home}/.anacrontab ] || cp ${dots}/.anacrontab ${home}/.anacrontab
