#!/bin/sh
dots=${1:-~/.nix-profile/share/home}
home=${2:-~}
# Symlink all the config files
mkdir -p ${home}/.config
for d in $(ls ${dots}/config); do
    [ -e ${home}/.config/$d ] || ln -s ${dots}/config/$d ${home}/.config/$d
done
# Symlink home dir dot files
[ -e ${home}/.zshenv ] || ln -s ${dots}/.zshenv ${home}/.zshenv
# Copy the default files for environment specific configs
[ -e ${home}/.fishrc.fish ] || cp ${dots}/.fishrc.fish ${home}/.fishrc.fish
[ -e ${home}/.anacrontab ] || cp ${dots}/.anacrontab ${home}/.anacrontab
