#! /bin/sh

xsetroot -cursor_name left_ptr &

~/.fehbg
killall polybar

if [[ ! -z $( xrandr --listactivemonitors | grep "DP-3") ]]; then
  bspc monitor DP-3 -d 1 2 3 4 5 6 7 8 9 0
  bspc monitor DP-3 -g 1920x1080+0+0
  bspc desktop 1 -f
  polybar dp3 &
else
  bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0
  bspc monitor eDP-1 -g 1920x1200+0+0
  bspc desktop 1 -f
  polybar edp1 &
fi

bspc config border_width         0
bspc config window_gap          12
bspc config top_padding 0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled
bspc rule -a scratchpad state=floating layer=above sticky=on rectangle=600x400+1100+300

scratchpad &
