set-option -sg escape-time 10
set-option -ga terminal-overrides ",alacritty:Tc"
set -g default-terminal "alacritty"
set-option -g focus-events on

# Set new panes to open in current directory
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set -g base-index 1
set -g renumber-windows on
set-option -g status-position top

bind s display-popup -E "tmixer"
bind r run-shell "tmixer reset"

###########
# PLUGINS #
###########

if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

set -g status-style 'fg=white,bg=#2f2f2f'
set -g status-right ''
set -g status-left '   #S   '
set -g status-left-length 1000
set -g window-status-current-format '#[fg=black,bg=green] #I #W '
set -g window-status-format ' #I #W '

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"
run '~/.tmux/plugins/tpm/tpm'
